#!/usr/bin/env bash
# setup.sh — Interactive setup wizard for Mainlayer Docker integration.
#
# Run this once to generate a .env file and a docker-compose.yml configured
# for your environment.
#
# Usage:
#   bash setup.sh
#   bash setup.sh --non-interactive   # Use environment variables directly

set -euo pipefail

NON_INTERACTIVE=false
[[ "${1:-}" == "--non-interactive" ]] && NON_INTERACTIVE=true

# ── Colour helpers ────────────────────────────────────────────────────────────
if [[ -t 1 ]]; then
    BOLD='\033[1m'; RESET='\033[0m'
    GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; CYAN='\033[0;36m'
else
    BOLD=''; RESET=''; GREEN=''; YELLOW=''; RED=''; CYAN=''
fi

header() { printf "\n${BOLD}${CYAN}%s${RESET}\n" "$*"; }
info()   { printf "  ${GREEN}✔${RESET} %s\n" "$*"; }
warn()   { printf "  ${YELLOW}!${RESET} %s\n" "$*"; }
error()  { printf "  ${RED}✖${RESET} %s\n" "$*" >&2; }
prompt() { printf "  ${BOLD}%s${RESET} " "$*"; }

# ── Banner ────────────────────────────────────────────────────────────────────
header "Mainlayer Docker Setup"
printf "  Stripe for AI agents — https://mainlayer.xyz\n"
printf "  This wizard generates a .env file for your deployment.\n"

# ── Gather configuration ──────────────────────────────────────────────────────
header "Step 1: API Key"

if [[ "${NON_INTERACTIVE}" == "true" ]]; then
    MAINLAYER_API_KEY="${MAINLAYER_API_KEY:-}"
else
    prompt "Enter your Mainlayer API key (starts with ml_):"
    read -r MAINLAYER_API_KEY
fi

if [[ -z "${MAINLAYER_API_KEY}" ]]; then
    error "API key is required."
    printf "  Get yours at: https://dashboard.mainlayer.xyz/api-keys\n"
    exit 1
fi

if [[ "${MAINLAYER_API_KEY}" != ml_* ]]; then
    warn "Key does not start with 'ml_'. Please verify it is correct."
fi

# ── Base URL ──────────────────────────────────────────────────────────────────
header "Step 2: Base URL"

if [[ "${NON_INTERACTIVE}" == "true" ]]; then
    MAINLAYER_BASE_URL="${MAINLAYER_BASE_URL:-https://api.mainlayer.xyz}"
else
    prompt "Mainlayer API base URL [https://api.mainlayer.xyz]:"
    read -r USER_BASE_URL
    MAINLAYER_BASE_URL="${USER_BASE_URL:-https://api.mainlayer.xyz}"
fi

info "Using base URL: ${MAINLAYER_BASE_URL}"

# ── Log level ─────────────────────────────────────────────────────────────────
header "Step 3: Log Level"

if [[ "${NON_INTERACTIVE}" == "true" ]]; then
    MAINLAYER_LOG_LEVEL="${MAINLAYER_LOG_LEVEL:-info}"
else
    prompt "Log level (debug/info/warn/error) [info]:"
    read -r USER_LOG_LEVEL
    MAINLAYER_LOG_LEVEL="${USER_LOG_LEVEL:-info}"
fi

info "Log level: ${MAINLAYER_LOG_LEVEL}"

# ── Cache TTL ─────────────────────────────────────────────────────────────────
header "Step 4: Cache TTL"

if [[ "${NON_INTERACTIVE}" == "true" ]]; then
    MAINLAYER_CACHE_TTL="${MAINLAYER_CACHE_TTL:-300}"
else
    prompt "Verification cache TTL in seconds [300]:"
    read -r USER_TTL
    MAINLAYER_CACHE_TTL="${USER_TTL:-300}"
fi

info "Cache TTL: ${MAINLAYER_CACHE_TTL}s"

# ── Verify connectivity ───────────────────────────────────────────────────────
header "Step 5: Verifying API connectivity"

HTTP_STATUS=$(
    curl --silent \
         --output /dev/null \
         --write-out "%{http_code}" \
         --max-time 15 \
         --header "Authorization: Bearer ${MAINLAYER_API_KEY}" \
         "${MAINLAYER_BASE_URL}/health" \
    || echo "000"
)

case "${HTTP_STATUS}" in
    200)  info "API connection successful." ;;
    401)  error "Authentication failed. Check your API key."; exit 1 ;;
    403)  error "Forbidden. Your key may lack the required permissions."; exit 1 ;;
    000)  error "Cannot reach ${MAINLAYER_BASE_URL}. Check your network."; exit 1 ;;
    *)    warn "Unexpected response: HTTP ${HTTP_STATUS}. Proceeding anyway." ;;
esac

# ── Write .env ────────────────────────────────────────────────────────────────
header "Step 6: Writing .env"

ENV_FILE=".env"

if [[ -f "${ENV_FILE}" ]]; then
    warn ".env already exists — backing up to .env.bak"
    cp "${ENV_FILE}" "${ENV_FILE}.bak"
fi

cat > "${ENV_FILE}" <<EOF
# Mainlayer configuration — generated by setup.sh
# Do NOT commit this file to version control.

MAINLAYER_API_KEY=${MAINLAYER_API_KEY}
MAINLAYER_BASE_URL=${MAINLAYER_BASE_URL}
MAINLAYER_LOG_LEVEL=${MAINLAYER_LOG_LEVEL}
MAINLAYER_CACHE_TTL=${MAINLAYER_CACHE_TTL}
MAINLAYER_TIMEOUT=30
EOF

# Secure the file
chmod 600 "${ENV_FILE}"
info "Written: ${ENV_FILE} (permissions: 600)"

# ── Check .gitignore ──────────────────────────────────────────────────────────
if [[ -f ".gitignore" ]]; then
    if ! grep -q "^\.env$" .gitignore 2>/dev/null; then
        echo ".env" >> .gitignore
        info "Added .env to .gitignore"
    fi
else
    echo ".env" > .gitignore
    info "Created .gitignore with .env entry"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
header "Setup complete"
printf "  Start your stack with:\n"
printf "\n"
printf "    ${BOLD}docker compose up${RESET}\n"
printf "\n"
printf "  Documentation: https://docs.mainlayer.xyz/docker\n\n"
